"""employees table updated

Revision ID: 5edd6f86a0b7
Revises: fd6c60277aeb
Create Date: 2026-09-14 18:01:55.555267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edd6f86a0b7'
down_revision: Union[str, Sequence[str], None] = 'fd6c60277aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'fired_at',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'fired_at',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
