"""branches is updated

Revision ID: 61ffa174419b
Revises: 6b395de4f3d8
Create Date: 2026-09-08 11:34:47.521445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ffa174419b'
down_revision: Union[str, Sequence[str], None] = '6b395de4f3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'branches', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='unique')
    # ### end Alembic commands ###
