"""branches and rooms tables added

Revision ID: 9ca5f7f4f550
Revises: 61ffa174419b
Create Date: 2026-09-12 10:52:57.037655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ca5f7f4f550'
down_revision: Union[str, Sequence[str], None] = '61ffa174419b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holidays')
    op.drop_table('settings')
    op.drop_column('branches', 'timezone')
    op.create_foreign_key(None, 'rooms', 'branches', ['branch_id'], ['id'])
    op.drop_column('rooms', 'has_projector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('has_projector', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.add_column('branches', sa.Column('timezone', mysql.VARCHAR(length=50), nullable=False))
    op.create_table('settings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('holidays',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('is_working', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
