"""employees table updated

Revision ID: fd6c60277aeb
Revises: 4ac9eea82c1e
Create Date: 2026-09-14 17:58:04.018733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fd6c60277aeb'
down_revision: Union[str, Sequence[str], None] = '4ac9eea82c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('employees_ibfk_1'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'branches', ['branch_id'], ['id'])
    op.drop_column('employees', 'branch')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('branch', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_ibfk_1'), 'employees', 'branches', ['branch'], ['id'])
    op.drop_column('employees', 'branch_id')
    # ### end Alembic commands ###
